//Next Action Item: Test Scripts
[
    "// Convert XML response to JSON",
    "var responseJson = xml2Json(pm.response.text());",
    "",
    "// Validate Status Code",
    "pm.test(\"Status code is 200\", function () {",
    "    pm.response.to.have.status(200);",
    "});",
    "",
    "// Validate MsgRefNo is Present",
    "pm.test(\"MsgRefNo exists\", function () {",
    "    pm.expect(responseJson['soapenv:Envelope']['soapenv:Body'].Message.Header.MsgRefNo).to.exist;",
    "});",
    "",
    "// Validate MsgRefNo Starts with 'AP'",
    "pm.test(\"MsgRefNo starts with 'AP'\", function () {",
    "    pm.expect(responseJson['soapenv:Envelope']['soapenv:Body'].Message.Header.MsgRefNo).to.include(\"AP\");",
    "});",
    "",
    "// Validate ExtTrxnCd is REAIDC10",
    "pm.test(\"ExtTrxnCd is REAIDC10\", function () {",
    "    pm.expect(responseJson['soapenv:Envelope']['soapenv:Body'].Message.Header.ExtTrxnCd).to.eql(\"REAIDC10\");",
    "});",
    "",
    "// Validate Error Code is 01",
    "pm.test(\"Error Code is 01\", function () {",
    "    pm.expect(responseJson['soapenv:Envelope']['soapenv:Body'].Message.Header.ErrCode).to.eql(\"01\");",
    "});",
    "",
    "// Validate DestQueueMgr is UMYQMB02",
    "pm.test(\"DestQueueMgr is UMYQMB02\", function () {",
    "    pm.expect(responseJson['soapenv:Envelope']['soapenv:Body'].Message.Header.DestQueueMgr).to.eql(\"UMYQMB02\");",
    "});",
    ""
]